# Generated by Django 6.0.2 on 2026-06-17 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoNet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OurPublication',
            new_name='Publication',
        ),
    ]
