# Generated by Django 6.0.2 on 2026-06-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoNet', '0003_videonews_remove_news_photo_newsphotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brochures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='Brochures/')),
                ('time_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('structure', models.CharField(verbose_name=[('Leadership', 'Rahbariyat'), ('Director_Advisor', 'Direktor Maslahatchisi'), ('Departments', 'Boshqarmalar'), ('Sections', "Bo'limlar")])),
                ('photo', models.ImageField(blank=True, upload_to='Leaders/')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='videonews',
            name='news_type',
            field=models.CharField(choices=[('Videos', 'Videolar'), ('Digests', 'Dayjestlar'), ('Podcasts', 'Podkastlar'), ('InnoTime', 'InnoTime'), ('Interviews', 'Intervyular')], default=('Videos', 'Videolar')),
        ),
    ]
