# Generated by Django 6.0.2 on 2026-06-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoNet', '0004_brochures_leadership_vacancies_videonews_news_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magazinesurl',
            old_name='magazine',
            new_name='publication',
        ),
    ]
