# Generated by Django 6.0.2 on 2026-06-18 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoNet', '0005_rename_magazine_magazinesurl_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='short_topic',
        ),
    ]
