# Generated by Django 6.0.2 on 2026-06-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoNet', '0006_remove_publication_short_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='url',
            field=models.CharField(default='https://www.youtube.com/', max_length=255),
        ),
    ]
