# Generated by Django 6.0.2 on 2026-06-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoNet', '0007_publication_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoSySsrc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('url', models.CharField(choices=[('Information System', 'Axborot tizimlari'), ('Data Analys', "Ma'lumotlarni tahlil qilish")])),
            ],
        ),
        migrations.AlterField(
            model_name='leadership',
            name='structure',
            field=models.CharField(choices=[('Leadership', 'Rahbariyat'), ('Director_Advisor', 'Direktor Maslahatchisi'), ('Departments', 'Boshqarmalar'), ('Sections', "Bo'limlar")]),
        ),
        migrations.AlterField(
            model_name='magazinesurl',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Magazines/'),
        ),
        migrations.AlterField(
            model_name='newsphotos',
            name='photo',
            field=models.ImageField(blank=True, upload_to='News/'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Partners/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Projects/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Publication/'),
        ),
    ]
