# Generated by Django 6.0.2 on 2026-06-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoNet', '0008_infosyssrc_alter_leadership_structure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosyssrc',
            name='type',
            field=models.CharField(choices=[('Information System', 'Axborot tizimlari'), ('Data Analys', "Ma'lumotlarni tahlil qilish")], default='Information System'),
        ),
        migrations.AlterField(
            model_name='infosyssrc',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
