# Generated by Django 6.0.2 on 2026-06-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoNet', '0010_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='description',
            field=models.TextField(),
        ),
    ]
