# Generated by Django 6.0.2 on 2026-06-19 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoNet', '0011_alter_vacancies_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Введите номер в формате +998901234567', regex='^\\+d{3}\\d{9}$')])),
                ('message', models.TextField()),
            ],
        ),
    ]
