# Generated by Django 6.0.2 on 2026-06-19 08:20

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoNet', '0012_usersmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersmessage',
            name='phone',
            field=models.CharField(default=2, max_length=14, validators=[django.core.validators.RegexValidator(message='Введите номер в формате +998901234567', regex='^\\+d{3}\\d{9}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersmessage',
            name='user_email',
            field=models.CharField(max_length=255),
        ),
    ]
