# Generated by Django 6.0.2 on 2026-06-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoNet', '0013_usersmessage_created_at_usersmessage_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmessage',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
