# Generated by Django 6.0.2 on 2026-06-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoNet', '0014_alter_usersmessage_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brochures',
            options={'ordering': ['-time_creation']},
        ),
        migrations.AlterModelOptions(
            name='magazinesurl',
            options={'ordering': ['-time_creation']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-time_creation']},
        ),
        migrations.AlterModelOptions(
            name='usersmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='videonews',
            options={'ordering': ['-time_creation']},
        ),
    ]
