# Generated by Django 6.0.2 on 2026-06-22 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoNet', '0015_alter_brochures_options_alter_magazinesurl_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsphotos',
            name='news_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='infoNet.news'),
        ),
    ]
