# Generated by Django 6.0.2 on 2026-06-23 06:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoNet', '0016_alter_newsphotos_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='infosyssrc',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='partners',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='videonews',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
