# Generated by Django 6.0.2 on 2026-06-24 05:18

import infoNet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoNet', '0018_alter_aboutus_content_alter_infosyssrc_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazinesurl',
            name='url',
        ),
        migrations.AddField(
            model_name='magazinesurl',
            name='upload',
            field=models.FileField(null=True, upload_to=infoNet.models.user_directory_path),
        ),
    ]
