# Generated by Django 6.0.2 on 2026-06-24 05:25

import django.db.models.deletion
import infoNet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoNet', '0019_remove_magazinesurl_url_magazinesurl_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazinesPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='Magazines/')),
                ('upload', models.FileField(null=True, upload_to=infoNet.models.user_directory_path)),
                ('time_creation', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='infoNet.publication')),
            ],
            options={
                'ordering': ['-time_creation'],
            },
        ),
        migrations.DeleteModel(
            name='MagazinesUrl',
        ),
    ]
