# Generated by Django 6.0.2 on 2026-06-24 05:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoNet', '0020_magazinespdf_delete_magazinesurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='editorial_board',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='general_information',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
