# Generated by Django 6.0.2 on 2026-06-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoNet', '0021_alter_publication_editorial_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosyssrc',
            name='type',
            field=models.CharField(choices=[('Information System', 'Axborot tizimlari'), ('Data Analys', "Ma'lumotlarni tahlil qilish")]),
        ),
        migrations.AlterField(
            model_name='videonews',
            name='news_type',
            field=models.CharField(choices=[('Videos', 'Videolar'), ('Digests', 'Dayjestlar'), ('Podcasts', 'Podkastlar'), ('InnoTime', 'InnoTime'), ('Interviews', 'Intervyular')]),
        ),
    ]
